# Do: pin all runtime dependencies in this spec with PEP 440 version specifiers
name: co2-reduction-run-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python~=3.8.8
  - pip~=20.2
  - tqdm
  - pip:
      - pytorch-lightning~=1.3.1
      - earthengine-api~=0.1.267
      - folium~=0.12.1
      - scikit-learn~=0.24.2
      - imbalanced-learn~=0.8.0
      - pandas~=1.2.4
      - git+https://github.com/radix-ai/agoro-field-boundary-detector.git
